/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const FireExtinguisherCertificateDto = IDL.Record({
  'certifiedBy' : IDL.Text,
  'nextDueDate' : IDL.Text,
  'clientName' : IDL.Text,
  'createdAt' : Time,
  'cylinderManufDate' : IDL.Text,
  'uniqueToken' : IDL.Text,
  'testedBy' : IDL.Text,
  'clientAddress' : IDL.Opt(IDL.Text),
  'updatedAt' : IDL.Opt(Time),
  'extinguisherType' : IDL.Text,
  'refillingCompany' : IDL.Text,
  'refillingDoneBy' : IDL.Text,
  'capacity' : IDL.Text,
  'refillingDate' : IDL.Text,
  'certificateNumber' : IDL.Opt(IDL.Nat),
  'remarks' : IDL.Opt(IDL.Text),
  'installationDate' : IDL.Text,
});
export const ContactInquiryDto = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
  'serviceNeeded' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCertificate' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'getAllCertificates' : IDL.Func(
      [],
      [IDL.Vec(FireExtinguisherCertificateDto)],
      ['query'],
    ),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(ContactInquiryDto)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCertificateByNumber' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(FireExtinguisherCertificateDto)],
      ['query'],
    ),
  'getCertificateByToken' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(FireExtinguisherCertificateDto)],
      ['query'],
    ),
  'getCertificatesByClientName' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(FireExtinguisherCertificateDto)],
      ['query'],
    ),
  'getInquiriesByName' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ContactInquiryDto)],
      ['query'],
    ),
  'getInquiriesByService' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ContactInquiryDto)],
      ['query'],
    ),
  'getInquiryByTimestamp' : IDL.Func([Time], [ContactInquiryDto], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCertificate' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'upsertInquiry' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const FireExtinguisherCertificateDto = IDL.Record({
    'certifiedBy' : IDL.Text,
    'nextDueDate' : IDL.Text,
    'clientName' : IDL.Text,
    'createdAt' : Time,
    'cylinderManufDate' : IDL.Text,
    'uniqueToken' : IDL.Text,
    'testedBy' : IDL.Text,
    'clientAddress' : IDL.Opt(IDL.Text),
    'updatedAt' : IDL.Opt(Time),
    'extinguisherType' : IDL.Text,
    'refillingCompany' : IDL.Text,
    'refillingDoneBy' : IDL.Text,
    'capacity' : IDL.Text,
    'refillingDate' : IDL.Text,
    'certificateNumber' : IDL.Opt(IDL.Nat),
    'remarks' : IDL.Opt(IDL.Text),
    'installationDate' : IDL.Text,
  });
  const ContactInquiryDto = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
    'serviceNeeded' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCertificate' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'getAllCertificates' : IDL.Func(
        [],
        [IDL.Vec(FireExtinguisherCertificateDto)],
        ['query'],
      ),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(ContactInquiryDto)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCertificateByNumber' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(FireExtinguisherCertificateDto)],
        ['query'],
      ),
    'getCertificateByToken' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(FireExtinguisherCertificateDto)],
        ['query'],
      ),
    'getCertificatesByClientName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(FireExtinguisherCertificateDto)],
        ['query'],
      ),
    'getInquiriesByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ContactInquiryDto)],
        ['query'],
      ),
    'getInquiriesByService' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ContactInquiryDto)],
        ['query'],
      ),
    'getInquiryByTimestamp' : IDL.Func([Time], [ContactInquiryDto], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCertificate' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'upsertInquiry' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };