/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactInquiryDto {
  'name' : string,
  'email' : string,
  'company' : [] | [string],
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
  'serviceNeeded' : string,
}
export interface FireExtinguisherCertificateDto {
  'certifiedBy' : string,
  'nextDueDate' : string,
  'clientName' : string,
  'createdAt' : Time,
  'cylinderManufDate' : string,
  'uniqueToken' : string,
  'testedBy' : string,
  'clientAddress' : [] | [string],
  'updatedAt' : [] | [Time],
  'extinguisherType' : string,
  'refillingCompany' : string,
  'refillingDoneBy' : string,
  'capacity' : string,
  'refillingDate' : string,
  'certificateNumber' : [] | [bigint],
  'remarks' : [] | [string],
  'installationDate' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCertificate' : ActorMethod<
    [
      string,
      [] | [string],
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      [] | [string],
    ],
    bigint
  >,
  'getAllCertificates' : ActorMethod<[], Array<FireExtinguisherCertificateDto>>,
  'getAllInquiries' : ActorMethod<[], Array<ContactInquiryDto>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCertificateByNumber' : ActorMethod<
    [bigint],
    [] | [FireExtinguisherCertificateDto]
  >,
  'getCertificateByToken' : ActorMethod<
    [string],
    [] | [FireExtinguisherCertificateDto]
  >,
  'getCertificatesByClientName' : ActorMethod<
    [string],
    Array<FireExtinguisherCertificateDto>
  >,
  'getInquiriesByName' : ActorMethod<[string], Array<ContactInquiryDto>>,
  'getInquiriesByService' : ActorMethod<[string], Array<ContactInquiryDto>>,
  'getInquiryByTimestamp' : ActorMethod<[Time], ContactInquiryDto>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCertificate' : ActorMethod<
    [
      bigint,
      string,
      [] | [string],
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      [] | [string],
    ],
    undefined
  >,
  'upsertInquiry' : ActorMethod<
    [string, [] | [string], string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];